import os
import sys
import sqlite3
import threading
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from flask import Flask, request, jsonify, render_template, redirect, send_from_directory, Response, make_response
from dotenv import load_dotenv

# Load environment variables from local .env if present
load_dotenv()

base_dir = os.path.dirname(os.path.abspath(__file__))
if base_dir not in sys.path:
    sys.path.insert(0, base_dir)

# Zoho Sheet integration
try:
    from zoho_sheet import append_inquiry_to_sheet
except ImportError:
    append_inquiry_to_sheet = None
    print("[WARN] zoho_sheet module not found — Zoho integration disabled")

from rac_api import rac_bp

# Resolve template and static folder relative to this file
site_root = os.path.abspath(os.path.join(base_dir, '..'))
template_dir = os.path.join(base_dir, '..', 'frontend', 'templates')
static_dir = os.path.join(base_dir, '..', 'frontend', 'static')
db_path = os.path.join(base_dir, 'database.db')
invoices_dir = os.path.join(site_root, 'tools', 'invoices')
trips_dir = os.path.join(site_root, 'tools', 'trips')
rac_dist_dir = os.path.join(site_root, 'rac', 'frontend', 'dist')
STAFF_COOKIE = 'smt_staff'
STAFF_TOKEN = 'smt-session-token'
RAC_FRONTEND_URL = os.environ.get('RAC_FRONTEND_URL', 'http://127.0.0.1:5173')

app = Flask(
    __name__,
    template_folder=os.path.abspath(template_dir),
    static_folder=os.path.abspath(static_dir)
)
@app.context_processor
def inject_now():
    return {'now': datetime.utcnow}


# Admin passcode for local authorization
ADMIN_PASSCODE = "5999"


def is_staff_request():
    if request.cookies.get(STAFF_COOKIE) == STAFF_TOKEN:
        return True
    auth_header = request.headers.get('Authorization')
    return auth_header == f"Bearer {STAFF_TOKEN}"


def require_staff_page():
    if is_staff_request():
        return None
    return redirect('/admin')


app.register_blueprint(rac_bp, url_prefix='/api/v1')


@app.before_request
def protect_rac_api():
    if not request.path.startswith('/api/v1'):
        return None
    if request.method == 'OPTIONS':
        return jsonify({'success': True})
    if not is_staff_request():
        return jsonify({'success': False, 'message': 'Unauthorized'}), 401
    return None


def send_inquiry_email(data):
    """Sends email asynchronously, fallback to file logging if SMTP not configured."""
    name = data.get('name', 'N/A')
    email = data.get('email', 'N/A')
    phone = data.get('phone', 'N/A')
    company = data.get('company', 'N/A')
    service_type = data.get('service_type', 'N/A')
    employee_count = data.get('employee_count', 0)
    details = data.get('details', 'N/A')
    
    subject = f"New SMT Quote Inquiry: {company} - {service_type}"
    
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; color: #333; }}
            .container {{ padding: 20px; border: 1px solid #ddd; max-width: 600px; border-radius: 8px; }}
            .header {{ background-color: #0e1322; color: #fff; padding: 15px; text-align: center; border-radius: 6px 6px 0 0; }}
            .info-table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            .info-table th, .info-table td {{ padding: 10px; border-bottom: 1px solid #eee; text-align: left; }}
            .info-table th {{ width: 35%; color: #555; }}
            .footer {{ margin-top: 30px; font-size: 0.8em; color: #777; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>Shree Maruthi Travels (SMT)</h2>
                <p>New Quote Inquiry Alert</p>
            </div>
            <table class="info-table">
                <tr><th>Client Name:</th><td>{name}</td></tr>
                <tr><th>Company:</th><td>{company}</td></tr>
                <tr><th>Email Address:</th><td>{email}</td></tr>
                <tr><th>Phone Number:</th><td>{phone}</td></tr>
                <tr><th>Service Type:</th><td>{service_type}</td></tr>
                <tr><th>Expected Commuters:</th><td>{employee_count}</td></tr>
                <tr><th>Route & Scheduling Details:</th><td>{details}</td></tr>
            </table>
            <div class="footer">
                <p>This is an automated operational alert generated by shreemaruthitravels.com portal.</p>
                <p>Supervisor Hotline: +91 9611975999</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    smtp_server = os.environ.get('SMTP_SERVER')
    smtp_port = os.environ.get('SMTP_PORT')
    smtp_user = os.environ.get('SMTP_USER')
    smtp_password = os.environ.get('SMTP_PASSWORD')
    
    receiver = os.environ.get('RECEIVER_EMAIL', 'shreemaruthitravels5999@gmail.com')
    
    if not all([smtp_server, smtp_port, smtp_user, smtp_password]):
        log_file = os.path.join(base_dir, 'emails_sent.log')
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        log_entry = f"========================================\n" \
                    f"TIMESTAMP: {timestamp}\n" \
                    f"SUBJECT: {subject}\n" \
                    f"TO: {receiver}\n" \
                    f"----------------------------------------\n" \
                    f"HTML CONTENT:\n{html_content}\n" \
                    f"========================================\n\n"
        try:
            with open(log_file, 'a', encoding='utf-8') as f:
                f.write(log_entry)
            print(f"[EMAIL DEV FALLBACK] Logged sent mail to {log_file}")
        except Exception as err:
            print(f"[EMAIL DEV FALLBACK] Failed to write to {log_file}: {str(err)}")
        return
        
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = smtp_user
        msg['To'] = receiver
        
        part_html = MIMEText(html_content, 'html')
        msg.attach(part_html)
        
        port_num = int(smtp_port)
        if port_num == 465:
            server = smtplib.SMTP_SSL(smtp_server, port_num)
        else:
            server = smtplib.SMTP(smtp_server, port_num)
            server.starttls()
            
        server.login(smtp_user, smtp_password)
        server.sendmail(smtp_user, receiver, msg.as_string())
        server.quit()
        print(f"[SMTP EMAIL] Successfully sent alert email to {receiver}")
    except Exception as smtp_err:
        print(f"[SMTP EMAIL ERROR] Failed to send email via SMTP: {str(smtp_err)}")
        log_file = os.path.join(base_dir, 'emails_sent.log')
        backup_timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        log_entry = f"========================================\n" \
                    f"TIMESTAMP: {backup_timestamp} (SMTP SEND ERROR: {str(smtp_err)})\n" \
                    f"SUBJECT: {subject}\n" \
                    f"TO: {receiver}\n" \
                    f"----------------------------------------\n" \
                    f"HTML CONTENT:\n{html_content}\n" \
                    f"========================================\n\n"
        try:
            with open(log_file, 'a', encoding='utf-8') as f:
                f.write(log_entry)
        except Exception as err:
            print(f"Failed to log email fallback: {str(err)}")


def get_db_connection():
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db_connection()
    cursor = conn.cursor()
    # Create inquiries table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS inquiries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL,
            phone TEXT NOT NULL,
            company TEXT,
            service_type TEXT NOT NULL,
            employee_count INTEGER DEFAULT 0,
            details TEXT,
            status TEXT DEFAULT 'Pending',
            created_at TEXT NOT NULL
        )
    ''')
    # Create chat_logs table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS chat_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id TEXT,
            user_message TEXT,
            bot_response TEXT,
            created_at TEXT NOT NULL
        )
    ''')
    # Create cabs table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS cabs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            reg_number TEXT UNIQUE NOT NULL,
            model TEXT NOT NULL,
            capacity INTEGER NOT NULL,
            fuel_type TEXT NOT NULL,
            status TEXT DEFAULT 'Active',
            is_ev INTEGER DEFAULT 0,
            battery_capacity TEXT,
            charge_status INTEGER,
            range_km INTEGER
        )
    ''')
    # Create cab_documents table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS cab_documents (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            cab_id INTEGER NOT NULL,
            doc_type TEXT NOT NULL,
            doc_number TEXT NOT NULL,
            expiry_date TEXT NOT NULL,
            FOREIGN KEY(cab_id) REFERENCES cabs(id) ON DELETE CASCADE
        )
    ''')
    # Create drivers table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS drivers (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            phone TEXT NOT NULL,
            license_number TEXT UNIQUE NOT NULL,
            license_expiry TEXT NOT NULL,
            status TEXT DEFAULT 'Active',
            assigned_cab_id INTEGER,
            FOREIGN KEY(assigned_cab_id) REFERENCES cabs(id) ON DELETE SET NULL
        )
    ''')
    # Create companies table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS companies (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            contact_person TEXT,
            contact_email TEXT,
            contact_phone TEXT,
            address TEXT
        )
    ''')
    # Create company_cabs table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS company_cabs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            company_id INTEGER NOT NULL,
            cab_id INTEGER NOT NULL,
            driver_id INTEGER NOT NULL,
            FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE CASCADE,
            FOREIGN KEY(cab_id) REFERENCES cabs(id) ON DELETE CASCADE,
            FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE CASCADE
        )
    ''')
    
    # Create trips table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS trips (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            cab_id INTEGER NOT NULL,
            driver_id INTEGER NOT NULL,
            company_id INTEGER NOT NULL,
            route_name TEXT NOT NULL,
            status TEXT DEFAULT 'Scheduled',
            progress REAL DEFAULT 0.0,
            speed INTEGER DEFAULT 0,
            eta TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(cab_id) REFERENCES cabs(id) ON DELETE CASCADE,
            FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE CASCADE,
            FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE CASCADE
        )
    ''')
    
    # Create trip_passengers table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS trip_passengers (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            trip_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            stop_name TEXT NOT NULL,
            status TEXT DEFAULT 'Pending',
            FOREIGN KEY(trip_id) REFERENCES trips(id) ON DELETE CASCADE
        )
    ''')
    
    # Create safety_alerts table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS safety_alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            trip_id INTEGER NOT NULL,
            alert_type TEXT NOT NULL,
            details TEXT NOT NULL,
            status TEXT DEFAULT 'Active',
            created_at TEXT NOT NULL,
            FOREIGN KEY(trip_id) REFERENCES trips(id) ON DELETE CASCADE
        )
    ''')
    
    # Seed cabs if empty
    cursor.execute('SELECT COUNT(*) FROM cabs')
    if cursor.fetchone()[0] == 0:
        cabs_data = [
            ("KA-05-MB-2041", "Toyota Innova Crysta", 7, "Diesel", "Active", 0, None, None, None),
            ("KA-03-EX-9988", "Tata Tigor EV", 4, "EV", "Active", 1, "26 kWh", 82, 170),
            ("KA-01-EE-5412", "BYD e6 EV", 5, "EV", "Active", 1, "71.7 kWh", 95, 410),
            ("KA-04-MM-1024", "Maruti Suzuki Dzire", 4, "Petrol", "Maintenance", 0, None, None, None),
            ("KA-02-TT-4455", "Force Urbania TT", 17, "Diesel", "Active", 0, None, None, None)
        ]
        cursor.executemany('''
            INSERT INTO cabs (reg_number, model, capacity, fuel_type, status, is_ev, battery_capacity, charge_status, range_km)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', cabs_data)
        
        # Seed documents for some of the cabs
        cursor.execute("SELECT id, reg_number FROM cabs")
        cab_ids = {row['reg_number']: row['id'] for row in cursor.fetchall()}
        
        docs_data = [
            (cab_ids["KA-05-MB-2041"], "Insurance", "INS-8849201", "2027-04-15"),
            (cab_ids["KA-05-MB-2041"], "Permit", "PMT-002934", "2026-07-10"),
            (cab_ids["KA-03-EX-9988"], "Insurance", "INS-7729103", "2026-05-10"),
            (cab_ids["KA-03-EX-9988"], "Fitness", "FIT-112204", "2027-01-20"),
            (cab_ids["KA-01-EE-5412"], "Insurance", "INS-6612904", "2026-12-05"),
            (cab_ids["KA-04-MM-1024"], "Road Tax", "TAX-445520", "2026-06-01")
        ]
        cursor.executemany('''
            INSERT INTO cab_documents (cab_id, doc_type, doc_number, expiry_date)
            VALUES (?, ?, ?, ?)
        ''', docs_data)
        
        # Seed drivers
        drivers_data = [
            ("Ramesh Kumar", "+91 9845012345", "DL-KA052021008", "2028-10-12", "Active", cab_ids["KA-05-MB-2041"]),
            ("Suresh Gowda", "+91 9900112233", "DL-KA032019941", "2026-07-05", "Active", cab_ids["KA-03-EX-9988"]),
            ("Anand Shekar", "+91 8877665544", "DL-KA012022093", "2029-01-15", "Active", cab_ids["KA-01-EE-5412"]),
            ("Manjunath V.", "+91 7766554433", "DL-KA042018221", "2026-04-20", "Active", cab_ids["KA-04-MM-1024"]),
            ("Harish K.", "+91 9123456789", "DL-KA022020492", "2027-08-30", "Active", cab_ids["KA-02-TT-4455"])
        ]
        cursor.executemany('''
            INSERT INTO drivers (name, phone, license_number, license_expiry, status, assigned_cab_id)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', drivers_data)
        
        # Seed companies
        companies_data = [
            ("Amazon Bangalore", "Priya Nair", "priya.nair@amazon.com", "+91 8041002000", "Amazon Development Centre, Mahadevapura, Bangalore"),
            ("TCS Whitefield", "Kiran Shah", "kiran.shah@tcs.com", "+91 8067823900", "TCS Vydehi RC, Whitefield, Bangalore"),
            ("Optum Bellandur", "Sanjay Rao", "sanjay.rao@optum.com", "+91 8049301030", "Eco Space, Bellandur, Bangalore")
        ]
        cursor.executemany('''
            INSERT INTO companies (name, contact_person, contact_email, contact_phone, address)
            VALUES (?, ?, ?, ?, ?)
        ''', companies_data)
        
        # Get company IDs
        cursor.execute("SELECT id, name FROM companies")
        company_ids = {row['name']: row['id'] for row in cursor.fetchall()}
        
        # Get driver IDs
        cursor.execute("SELECT id, name FROM drivers")
        driver_ids = {row['name']: row['id'] for row in cursor.fetchall()}
        
        # Seed assignments
        assignments_data = [
            (company_ids["Amazon Bangalore"], cab_ids["KA-05-MB-2041"], driver_ids["Ramesh Kumar"]),
            (company_ids["Amazon Bangalore"], cab_ids["KA-03-EX-9988"], driver_ids["Suresh Gowda"]),
            (company_ids["TCS Whitefield"], cab_ids["KA-01-EE-5412"], driver_ids["Anand Shekar"]),
            (company_ids["Optum Bellandur"], cab_ids["KA-02-TT-4455"], driver_ids["Harish K."])
        ]
        cursor.executemany('''
            INSERT INTO company_cabs (company_id, cab_id, driver_id)
            VALUES (?, ?, ?)
        ''', assignments_data)

    conn.commit()
    conn.close()


# Ensure DB exists
init_db()


@app.route('/')
def home():
    return render_template('index.html')


@app.route('/admin')
def admin():
    return render_template('admin.html')


@app.route('/services')
def services():
    return render_template('services.html')


@app.route('/fleet')
def fleet():
    return render_template('fleet.html')


@app.route('/about')
def about():
    return render_template('about.html')


@app.route('/contact')
def contact():
    return render_template('contact.html')


@app.route('/api/places-autocomplete', methods=['GET'])
def places_autocomplete():
    import urllib.request
    import urllib.parse
    import json
    
    query = request.args.get('q', '').strip()
    if not query or len(query) < 3:
        return jsonify([])
    
    # Query OpenStreetMap Nominatim API for India (restrict to countrycodes=in)
    encoded_query = urllib.parse.quote(query)
    url = f"https://nominatim.openstreetmap.org/search?format=json&q={encoded_query}&countrycodes=in&limit=5"
    
    try:
        req = urllib.request.Request(
            url,
            headers={
                'User-Agent': 'ShreeMaruthiTravelsWebsite/1.0 (shreemaruthitravels5999@gmail.com)'
            }
        )
        with urllib.request.urlopen(req, timeout=5) as response:
            data = json.loads(response.read().decode('utf-8'))
            results = []
            for item in data:
                results.append({
                    "display_name": item.get('display_name', ''),
                    "lat": item.get('lat'),
                    "lon": item.get('lon')
                })
            return jsonify(results)
    except Exception as e:
        print(f"[AUTOCOMPLETE ERROR] Failed to query Nominatim: {str(e)}")
        # Fallback to predefined key locations in Bangalore for reliability
        mock_places = [
            "Gubbalala, Jayanagar Housing Society Layout, Bangalore",
            "Whitefield, Bangalore, Karnataka",
            "Electronic City, Bangalore, Karnataka",
            "Kempegowda International Airport (BLR), Devanahalli, Bangalore",
            "Majestic (Kempegowda Bus Station), Bangalore",
            "Indiranagar, Bangalore, Karnataka",
            "Koramangala, Bangalore, Karnataka",
            "Hebbal, Bangalore, Karnataka",
            "Outer Ring Road, Bellandur, Bangalore",
            "Silk Board Junction, Hosur Road, Bangalore",
            "Yelahanka, Bangalore, Karnataka",
            "Jayanagar, Bangalore, Karnataka",
            "JP Nagar, Bangalore, Karnataka",
            "BTM Layout, Bangalore, Karnataka",
            "HSR Layout, Bangalore, Karnataka",
            "Marathahalli, Bangalore, Karnataka",
            "Yeshwanthpur, Bangalore, Karnataka",
            "Rajajinagar, Bangalore, Karnataka",
            "Malleshwaram, Bangalore, Karnataka",
            "Bannerghatta Road, Bangalore, Karnataka"
        ]
        filtered = [p for p in mock_places if query.lower() in p.lower()]
        return jsonify([{"display_name": p, "lat": "0", "lon": "0"} for p in filtered])


# --- REST APIs ---

@app.route('/api/inquiries', methods=['POST'])
def create_inquiry():
    try:
        data = request.get_json()
        if not data:
            return jsonify({"error": "No input data provided"}), 400

        name = data.get('name')
        email = data.get('email')
        phone = data.get('phone')
        service_type = data.get('service_type')
        company = data.get('company', '')
        employee_count = data.get('employee_count', 0)
        details = data.get('details', '')

        if not all([name, email, phone, service_type]):
            return jsonify({"error": "Missing required fields (name, email, phone, service_type)"}), 400

        conn = get_db_connection()
        cursor = conn.cursor()
        created_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        cursor.execute('''
            INSERT INTO inquiries (name, email, phone, company, service_type, employee_count, details, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ''', (name, email, phone, company, service_type, employee_count, details, created_at))

        conn.commit()
        conn.close()

        # Build inquiry data dict for notifications
        inquiry_data = {
            "name": name,
            "company": company,
            "email": email,
            "phone": phone,
            "service_type": service_type,
            "employee_count": employee_count,
            "details": details
        }

        # Push to Zoho Sheet asynchronously
        if append_inquiry_to_sheet:
            threading.Thread(
                target=append_inquiry_to_sheet,
                args=(inquiry_data,)
            ).start()

        # Trigger email notification asynchronously
        threading.Thread(target=send_inquiry_email, args=(inquiry_data,)).start()

        return jsonify({"message": "Inquiry submitted successfully", "status": "success"}), 201
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/api/admin/login', methods=['POST'])
def admin_login():
    data = request.get_json()
    passcode = data.get('passcode')
    if passcode == ADMIN_PASSCODE:
        resp = make_response(jsonify({"authenticated": True, "token": STAFF_TOKEN}), 200)
        resp.set_cookie(STAFF_COOKIE, STAFF_TOKEN, httponly=True, samesite='Lax', max_age=60 * 60 * 12)
        return resp
    return jsonify({"authenticated": False, "error": "Invalid passcode"}), 401


@app.route('/api/admin/logout', methods=['POST'])
def admin_logout():
    resp = make_response(jsonify({"ok": True}), 200)
    resp.delete_cookie(STAFF_COOKIE)
    return resp


@app.route('/api/inquiries', methods=['GET'])
def get_inquiries():
    # Basic Authorization check
    auth_header = request.headers.get('Authorization')
    if not auth_header or auth_header != "Bearer smt-session-token":
        return jsonify({"error": "Unauthorized Access"}), 401

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM inquiries ORDER BY created_at DESC')
    rows = cursor.fetchall()
    conn.close()

    inquiries = []
    for r in rows:
        inquiries.append({
            "id": r["id"],
            "name": r["name"],
            "email": r["email"],
            "phone": r["phone"],
            "company": r["company"],
            "service_type": r["service_type"],
            "employee_count": r["employee_count"],
            "details": r["details"],
            "status": r["status"],
            "created_at": r["created_at"]
        })

    return jsonify(inquiries)


@app.route('/api/inquiries/<int:inquiry_id>/status', methods=['POST'])
def update_inquiry_status(inquiry_id):
    auth_header = request.headers.get('Authorization')
    if not auth_header or auth_header != "Bearer smt-session-token":
        return jsonify({"error": "Unauthorized Access"}), 401

    data = request.get_json()
    status = data.get('status')
    if status not in ['Pending', 'In Progress', 'Completed']:
        return jsonify({"error": "Invalid status value"}), 400

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('UPDATE inquiries SET status = ? WHERE id = ?', (status, inquiry_id))
    conn.commit()
    conn.close()

    return jsonify({"message": f"Inquiry status updated to {status}"})


@app.route('/api/stats', methods=['GET'])
def get_stats():
    auth_header = request.headers.get('Authorization')
    if not auth_header or auth_header != "Bearer smt-session-token":
        return jsonify({"error": "Unauthorized Access"}), 401

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute('SELECT COUNT(*) FROM inquiries')
    total = cursor.fetchone()[0]

    cursor.execute('SELECT COUNT(*) FROM inquiries WHERE status = "Pending"')
    pending = cursor.fetchone()[0]

    cursor.execute('SELECT COUNT(*) FROM inquiries WHERE status = "In Progress"')
    in_progress = cursor.fetchone()[0]

    cursor.execute('SELECT COUNT(*) FROM inquiries WHERE status = "Completed"')
    completed = cursor.fetchone()[0]

    # Service distribution
    cursor.execute('SELECT service_type, COUNT(*) FROM inquiries GROUP BY service_type')
    services = {row[0]: row[1] for row in cursor.fetchall()}

    conn.close()

    return jsonify({
        "total": total,
        "pending": pending,
        "in_progress": in_progress,
        "completed": completed,
        "services": services
    })


@app.route('/api/chat', methods=['POST'])
def helpdesk_chat():
    try:
        data = request.get_json()
        user_message = data.get('message', '').strip().lower()
        session_id = data.get('session_id', 'anonymous')

        if not user_message:
            return jsonify({"response": "I didn't receive any message. How can I assist you today?"})

        # Smart Response Engine based on SMT info
        response = ""

        if any(w in user_message for w in ["hi", "hello", "hey", "greetings"]):
            response = "Hello! Welcome to Shree Maruthi Travels (SMT) Helpdesk. How can I assist you with your transportation needs today?"
        
        elif any(w in user_message for w in ["contact", "phone", "number", "call", "proprietor", "owner"]):
            response = ("You can contact SMT at +91 9611975999. "
                        "Our proprietor, Mr. Byre Gowda, will be glad to assist you. "
                        "Alternatively, you can email us at shreemaruthitravels5999@gmail.com.")
        
        elif any(w in user_message for w in ["email", "mail"]):
            response = "You can write to us at shreemaruthitravels5999@gmail.com for any queries, bookings, or formal proposals."

        elif any(w in user_message for w in ["address", "location", "office", "where"]):
            response = ("Our head office is located at: "
                        "No. 374C, 1st Floor, 4th Cross, 9th Main, 1st Stage, Gubbalala, "
                        "Near Pride Apartment, Jayanagar Housing Society Layout, Bangalore – 560061.")

        elif any(w in user_message for w in ["services", "what do you do", "type of"]):
            response = ("We specialize in Employee Transportation Services (ETS) since 2017. "
                        "Additionally, we offer:\n"
                        "1. Corporate ETS (tailored route schedules)\n"
                        "2. Rental Services (well-maintained cars/buses for short/long term)\n"
                        "3. Airport Pick-up & Drop (punctual transfers)\n"
                        "4. Outstation Travels (comfort travel with professional drivers)")

        elif any(w in user_message for w in ["fleet", "vehicle", "car", "bus", "sedan", "tempo", "urbania", "crysta", "dzire", "tigor"]):
            response = ("Our premium corporate fleet includes:\n"
                        "• Maruti Suzuki Dzire (Reliable Premium Sedan - 4 Pax)\n"
                        "• Tata Tigor EV (Sustainable Electric Sedan - 4 Pax)\n"
                        "• Toyota Innova Crysta (Spacious Executive MPV - 6-7 Pax)\n"
                        "• Force Urbania TT (Next-Gen Premium Mini-Bus - 12-17 Pax)\n"
                        "• Premium Commuter Bus (Normal Commuter Bus Facility - 30-50 Pax)\n\n"
                        "All SMT vehicles are equipped with GPS tracking, First-Aid kits, stereos, and are operated by professional, verified drivers.")

        elif any(w in user_message for w in ["accessory", "accessories", "gps", "safety", "stereo"]):
            response = ("To ensure optimal safety and passenger comfort, all our vehicles are equipped with: "
                        "GPS tracking, First-Aid kits, stereos, and our drivers are equipped with mobile phones for seamless communication.")

        elif any(w in user_message for w in ["mission", "vision", "goal", "why choose"]):
            response = ("Our Mission is to emerge as a leading corporate transportation service provider in Bangalore. "
                        "Our Vision focuses on 'Proactive Operations' (anticipating challenges before they occur), "
                        "'Prevention over Cure' (strict safety/reliability priorities), and 'Continuous Improvement'.")

        elif any(w in user_message for w in ["partner", "client", "customer", "amazon", "tcs", "ola", "uber"]):
            response = ("We have partnered with leading organizations including Amazon, TCS (Tata Consultancy Services), "
                        "Optum, Fidelity, Ola, Uber, Nutanix, Golden Ikon, and Srinivasa Rent-A-Cab.")

        elif any(w in user_message for w in ["book", "price", "rate", "cost", "quote", "hire"]):
            response = ("For custom quotes and bookings, please complete the multi-step Quote form available in the "
                        "'Book Now' section of our website. SMT offers highly competitive and cost-optimized rates tailored "
                        "specifically to your requirements!")

        elif any(w in user_message for w in ["helpdesk", "support", "time", "hours", "operation"]):
            response = "Our operations and helpdesk support are available 24/7. We provide continuous support to ensure smooth transportation operations at all hours!"

        else:
            response = ("I'm sorry, I didn't quite catch that. Here is what I can help you with:\n"
                        "- Details on SMT Services & Fleet Accessories\n"
                        "- Office Address and Mr. Byre Gowda's contact details\n"
                        "- Our Corporate Partners & Values\n"
                        "- Booking inquiry procedures. Feel free to ask!")

        # Log chat to SQLite DB
        conn = get_db_connection()
        cursor = conn.cursor()
        created_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        cursor.execute('''
            INSERT INTO chat_logs (session_id, user_message, bot_response, created_at)
            VALUES (?, ?, ?, ?)
        ''', (session_id, user_message, response, created_at))
        conn.commit()
        conn.close()

        return jsonify({"response": response})
    except Exception as e:
        return jsonify({"response": f"Error handling request: {str(e)}"}), 500


def check_admin_auth():
    return is_staff_request()


@app.route('/api/admin/cabs', methods=['GET', 'POST'])
def handle_cabs():
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    if request.method == 'GET':
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM cabs ORDER BY is_ev DESC, reg_number ASC')
        rows = cursor.fetchall()
        conn.close()
        
        cabs = []
        for r in rows:
            cabs.append({
                "id": r["id"],
                "reg_number": r["reg_number"],
                "model": r["model"],
                "capacity": r["capacity"],
                "fuel_type": r["fuel_type"],
                "status": r["status"],
                "is_ev": r["is_ev"],
                "battery_capacity": r["battery_capacity"],
                "charge_status": r["charge_status"],
                "range_km": r["range_km"]
            })
        return jsonify(cabs)
        
    elif request.method == 'POST':
        data = request.get_json()
        reg_number = data.get('reg_number')
        model = data.get('model')
        capacity = data.get('capacity')
        fuel_type = data.get('fuel_type')
        status = data.get('status', 'Active')
        is_ev = int(data.get('is_ev', 0))
        battery_capacity = data.get('battery_capacity')
        charge_status = data.get('charge_status')
        range_km = data.get('range_km')
        
        # Parse numeric values safely
        try:
            capacity = int(capacity)
        except:
            capacity = 4
            
        if charge_status is not None and charge_status != "":
            try: charge_status = int(charge_status)
            except: charge_status = None
        else:
            charge_status = None
            
        if range_km is not None and range_km != "":
            try: range_km = int(range_km)
            except: range_km = None
        else:
            range_km = None
        
        if not reg_number or not model or not capacity or not fuel_type:
            return jsonify({"error": "Missing required cab fields"}), 400
            
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('''
                INSERT INTO cabs (reg_number, model, capacity, fuel_type, status, is_ev, battery_capacity, charge_status, range_km)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (reg_number, model, capacity, fuel_type, status, is_ev, battery_capacity, charge_status, range_km))
            conn.commit()
            conn.close()
            return jsonify({"message": "Cab added successfully"}), 201
        except sqlite3.IntegrityError:
            return jsonify({"error": "Cab with this registration number already exists"}), 400
        except Exception as e:
            return jsonify({"error": str(e)}), 500


@app.route('/api/admin/cabs/<int:cab_id>', methods=['PUT', 'DELETE'])
def handle_cab_detail(cab_id):
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    if request.method == 'PUT':
        data = request.get_json()
        reg_number = data.get('reg_number')
        model = data.get('model')
        capacity = data.get('capacity')
        fuel_type = data.get('fuel_type')
        status = data.get('status')
        is_ev = int(data.get('is_ev', 0))
        battery_capacity = data.get('battery_capacity')
        charge_status = data.get('charge_status')
        range_km = data.get('range_km')
        
        # Parse numeric values safely
        try:
            capacity = int(capacity)
        except:
            capacity = 4
            
        if charge_status is not None and charge_status != "":
            try: charge_status = int(charge_status)
            except: charge_status = None
        else:
            charge_status = None
            
        if range_km is not None and range_km != "":
            try: range_km = int(range_km)
            except: range_km = None
        else:
            range_km = None
        
        if not reg_number or not model or not capacity or not fuel_type:
            return jsonify({"error": "Missing required fields"}), 400
            
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('''
                UPDATE cabs 
                SET reg_number=?, model=?, capacity=?, fuel_type=?, status=?, is_ev=?, battery_capacity=?, charge_status=?, range_km=?
                WHERE id=?
            ''', (reg_number, model, capacity, fuel_type, status, is_ev, battery_capacity, charge_status, range_km, cab_id))
            conn.commit()
            conn.close()
            return jsonify({"message": "Cab updated successfully"})
        except Exception as e:
            return jsonify({"error": str(e)}), 500
            
    elif request.method == 'DELETE':
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('UPDATE drivers SET assigned_cab_id = NULL WHERE assigned_cab_id = ?', (cab_id,))
            cursor.execute('DELETE FROM company_cabs WHERE cab_id = ?', (cab_id,))
            cursor.execute('DELETE FROM cab_documents WHERE cab_id = ?', (cab_id,))
            cursor.execute('DELETE FROM cabs WHERE id = ?', (cab_id,))
            conn.commit()
            conn.close()
            return jsonify({"message": "Cab deleted successfully"})
        except Exception as e:
            return jsonify({"error": str(e)}), 500


@app.route('/api/admin/cabs/<int:cab_id>/documents', methods=['GET', 'POST'])
def handle_cab_documents(cab_id):
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    if request.method == 'GET':
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM cab_documents WHERE cab_id = ? ORDER BY expiry_date ASC', (cab_id,))
        rows = cursor.fetchall()
        conn.close()
        
        docs = []
        for r in rows:
            docs.append({
                "id": r["id"],
                "cab_id": r["cab_id"],
                "doc_type": r["doc_type"],
                "doc_number": r["doc_number"],
                "expiry_date": r["expiry_date"]
            })
        return jsonify(docs)
        
    elif request.method == 'POST':
        data = request.get_json()
        doc_type = data.get('doc_type')
        doc_number = data.get('doc_number')
        expiry_date = data.get('expiry_date')
        
        if not doc_type or not doc_number or not expiry_date:
            return jsonify({"error": "Missing required document fields"}), 400
            
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('''
                INSERT INTO cab_documents (cab_id, doc_type, doc_number, expiry_date)
                VALUES (?, ?, ?, ?)
            ''', (cab_id, doc_type, doc_number, expiry_date))
            conn.commit()
            conn.close()
            return jsonify({"message": "Document added successfully"}), 201
        except Exception as e:
            return jsonify({"error": str(e)}), 500


@app.route('/api/admin/documents/<int:doc_id>', methods=['DELETE'])
def delete_document(doc_id):
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute('DELETE FROM cab_documents WHERE id = ?', (doc_id,))
        conn.commit()
        conn.close()
        return jsonify({"message": "Document deleted successfully"})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/api/admin/drivers', methods=['GET', 'POST'])
def handle_drivers():
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    if request.method == 'GET':
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute('''
            SELECT drivers.*, cabs.reg_number as cab_reg, cabs.model as cab_model 
            FROM drivers 
            LEFT JOIN cabs ON drivers.assigned_cab_id = cabs.id 
            ORDER BY drivers.name ASC
        ''')
        rows = cursor.fetchall()
        conn.close()
        
        drivers = []
        for r in rows:
            drivers.append({
                "id": r["id"],
                "name": r["name"],
                "phone": r["phone"],
                "license_number": r["license_number"],
                "license_expiry": r["license_expiry"],
                "status": r["status"],
                "assigned_cab_id": r["assigned_cab_id"],
                "cab_reg": r["cab_reg"] if r["cab_reg"] else "Unassigned",
                "cab_model": r["cab_model"] if r["cab_model"] else ""
            })
        return jsonify(drivers)
        
    elif request.method == 'POST':
        data = request.get_json()
        name = data.get('name')
        phone = data.get('phone')
        license_number = data.get('license_number')
        license_expiry = data.get('license_expiry')
        status = data.get('status', 'Active')
        assigned_cab_id = data.get('assigned_cab_id')
        
        if assigned_cab_id == "" or assigned_cab_id == "None" or assigned_cab_id == "null" or assigned_cab_id is None:
            assigned_cab_id = None
        else:
            try: assigned_cab_id = int(assigned_cab_id)
            except: assigned_cab_id = None
            
        if not name or not phone or not license_number or not license_expiry:
            return jsonify({"error": "Missing required driver fields"}), 400
            
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('''
                INSERT INTO drivers (name, phone, license_number, license_expiry, status, assigned_cab_id)
                VALUES (?, ?, ?, ?, ?, ?)
            ''', (name, phone, license_number, license_expiry, status, assigned_cab_id))
            conn.commit()
            conn.close()
            return jsonify({"message": "Driver added successfully"}), 201
        except sqlite3.IntegrityError:
            return jsonify({"error": "License number already registered"}), 400
        except Exception as e:
            return jsonify({"error": str(e)}), 500


@app.route('/api/admin/drivers/<int:driver_id>', methods=['PUT', 'DELETE'])
def handle_driver_detail(driver_id):
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    if request.method == 'PUT':
        data = request.get_json()
        name = data.get('name')
        phone = data.get('phone')
        license_number = data.get('license_number')
        license_expiry = data.get('license_expiry')
        status = data.get('status')
        assigned_cab_id = data.get('assigned_cab_id')
        
        if assigned_cab_id == "" or assigned_cab_id == "None" or assigned_cab_id == "null" or assigned_cab_id is None:
            assigned_cab_id = None
        else:
            try: assigned_cab_id = int(assigned_cab_id)
            except: assigned_cab_id = None
            
        if not name or not phone or not license_number or not license_expiry:
            return jsonify({"error": "Missing required fields"}), 400
            
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('''
                UPDATE drivers 
                SET name=?, phone=?, license_number=?, license_expiry=?, status=?, assigned_cab_id=?
                WHERE id=?
            ''', (name, phone, license_number, license_expiry, status, assigned_cab_id, driver_id))
            conn.commit()
            conn.close()
            return jsonify({"message": "Driver updated successfully"})
        except Exception as e:
            return jsonify({"error": str(e)}), 500
            
    elif request.method == 'DELETE':
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('DELETE FROM company_cabs WHERE driver_id = ?', (driver_id,))
            cursor.execute('DELETE FROM drivers WHERE id = ?', (driver_id,))
            conn.commit()
            conn.close()
            return jsonify({"message": "Driver deleted successfully"})
        except Exception as e:
            return jsonify({"error": str(e)}), 500


@app.route('/api/admin/companies', methods=['GET', 'POST'])
def handle_companies():
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    if request.method == 'GET':
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM companies ORDER BY name ASC')
        rows = cursor.fetchall()
        conn.close()
        
        companies = []
        for r in rows:
            companies.append({
                "id": r["id"],
                "name": r["name"],
                "contact_person": r["contact_person"],
                "contact_email": r["contact_email"],
                "contact_phone": r["contact_phone"],
                "address": r["address"]
            })
        return jsonify(companies)
        
    elif request.method == 'POST':
        data = request.get_json()
        name = data.get('name')
        contact_person = data.get('contact_person')
        contact_email = data.get('contact_email')
        contact_phone = data.get('contact_phone')
        address = data.get('address')
        
        if not name:
            return jsonify({"error": "Company name is required"}), 400
            
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('''
                INSERT INTO companies (name, contact_person, contact_email, contact_phone, address)
                VALUES (?, ?, ?, ?, ?)
            ''', (name, contact_person, contact_email, contact_phone, address))
            conn.commit()
            conn.close()
            return jsonify({"message": "Company added successfully"}), 201
        except sqlite3.IntegrityError:
            return jsonify({"error": "Company with this name already exists"}), 400
        except Exception as e:
            return jsonify({"error": str(e)}), 500


@app.route('/api/admin/companies/<int:company_id>', methods=['PUT', 'DELETE'])
def handle_company_detail(company_id):
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    if request.method == 'PUT':
        data = request.get_json()
        name = data.get('name')
        contact_person = data.get('contact_person')
        contact_email = data.get('contact_email')
        contact_phone = data.get('contact_phone')
        address = data.get('address')
        
        if not name:
            return jsonify({"error": "Company name is required"}), 400
            
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('''
                UPDATE companies 
                SET name=?, contact_person=?, contact_email=?, contact_phone=?, address=?
                WHERE id=?
            ''', (name, contact_person, contact_email, contact_phone, address, company_id))
            conn.commit()
            conn.close()
            return jsonify({"message": "Company updated successfully"})
        except Exception as e:
            return jsonify({"error": str(e)}), 500
            
    elif request.method == 'DELETE':
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('DELETE FROM company_cabs WHERE company_id = ?', (company_id,))
            cursor.execute('DELETE FROM companies WHERE id = ?', (company_id,))
            conn.commit()
            conn.close()
            return jsonify({"message": "Company deleted successfully"})
        except Exception as e:
            return jsonify({"error": str(e)}), 500


@app.route('/api/admin/companies/<int:company_id>/assignments', methods=['GET', 'POST'])
def handle_company_assignments(company_id):
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    if request.method == 'GET':
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute('''
            SELECT company_cabs.id as assignment_id, cabs.id as cab_id, cabs.reg_number as cab_reg, cabs.model as cab_model,
                   drivers.id as driver_id, drivers.name as driver_name, drivers.phone as driver_phone
            FROM company_cabs
            JOIN cabs ON company_cabs.cab_id = cabs.id
            JOIN drivers ON company_cabs.driver_id = drivers.id
            WHERE company_cabs.company_id = ?
        ''', (company_id,))
        rows = cursor.fetchall()
        conn.close()
        
        assignments = []
        for r in rows:
            assignments.append({
                "assignment_id": r["assignment_id"],
                "cab_id": r["cab_id"],
                "cab_reg": r["cab_reg"],
                "cab_model": r["cab_model"],
                "driver_id": r["driver_id"],
                "driver_name": r["driver_name"],
                "driver_phone": r["driver_phone"]
            })
        return jsonify(assignments)
        
    elif request.method == 'POST':
        data = request.get_json()
        cab_id = data.get('cab_id')
        driver_id = data.get('driver_id')
        
        if not cab_id or not driver_id:
            return jsonify({"error": "Cab and Driver must be selected"}), 400
            
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute('''
                INSERT INTO company_cabs (company_id, cab_id, driver_id)
                VALUES (?, ?, ?)
            ''', (company_id, cab_id, driver_id))
            conn.commit()
            conn.close()
            return jsonify({"message": "Cab and Driver assigned successfully"}), 201
        except Exception as e:
            return jsonify({"error": str(e)}), 500


@app.route('/api/admin/assignments/<int:assignment_id>', methods=['DELETE'])
def delete_assignment(assignment_id):
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute('DELETE FROM company_cabs WHERE id = ?', (assignment_id,))
        conn.commit()
        conn.close()
        return jsonify({"message": "Assignment removed successfully"})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


# --- LIVE TRACKING & SIMULATION ENDPOINTS ---

@app.route('/api/admin/trips', methods=['GET'])
def get_trips():
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Fetch active trips
    cursor.execute('''
        SELECT t.*, c.reg_number as cab_reg, c.model as cab_model, c.fuel_type as cab_fuel, c.is_ev as cab_is_ev,
               d.name as driver_name, d.phone as driver_phone,
               co.name as company_name
        FROM trips t
        JOIN cabs c ON t.cab_id = c.id
        JOIN drivers d ON t.driver_id = d.id
        JOIN companies co ON t.company_id = co.id
        ORDER BY t.created_at DESC
    ''')
    rows = cursor.fetchall()
    
    trips = []
    for r in rows:
        trip_id = r["id"]
        # Fetch passengers
        cursor.execute('SELECT * FROM trip_passengers WHERE trip_id = ?', (trip_id,))
        pass_rows = cursor.fetchall()
        passengers = []
        for pr in pass_rows:
            passengers.append({
                "id": pr["id"],
                "name": pr["name"],
                "stop_name": pr["stop_name"],
                "status": pr["status"]
            })
        
        trips.append({
            "id": trip_id,
            "cab_id": r["cab_id"],
            "cab_reg": r["cab_reg"],
            "cab_model": r["cab_model"],
            "cab_fuel": r["cab_fuel"],
            "cab_is_ev": r["cab_is_ev"],
            "driver_id": r["driver_id"],
            "driver_name": r["driver_name"],
            "driver_phone": r["driver_phone"],
            "company_id": r["company_id"],
            "company_name": r["company_name"],
            "route_name": r["route_name"],
            "status": r["status"],
            "progress": r["progress"],
            "speed": r["speed"],
            "eta": r["eta"],
            "passengers": passengers,
            "created_at": r["created_at"]
        })
        
    conn.close()
    return jsonify(trips)


@app.route('/api/admin/safety-alerts', methods=['GET'])
def get_safety_alerts():
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('''
        SELECT s.*, t.route_name
        FROM safety_alerts s
        JOIN trips t ON s.trip_id = t.id
        ORDER BY s.created_at DESC
    ''')
    rows = cursor.fetchall()
    conn.close()
    
    alerts = []
    for r in rows:
        alerts.append({
            "id": r["id"],
            "trip_id": r["trip_id"],
            "route_name": r["route_name"],
            "alert_type": r["alert_type"],
            "details": r["details"],
            "status": r["status"],
            "created_at": r["created_at"]
        })
    return jsonify(alerts)


@app.route('/api/admin/trips/optimize', methods=['POST'])
def optimize_trips():
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Fetch all Pending inquiries
    cursor.execute('SELECT * FROM inquiries WHERE status = "Pending"')
    inquiries = cursor.fetchall()
    
    if not inquiries:
        conn.close()
        return jsonify({"message": "No pending inquiries to optimize. Submit a booking quote from client homepage first."}), 200
        
    # Fetch available Active cabs
    cursor.execute('SELECT * FROM cabs WHERE status = "Active"')
    cabs = cursor.fetchall()
    
    # Fetch active drivers
    cursor.execute('SELECT * FROM drivers WHERE status = "Active"')
    drivers = cursor.fetchall()
    
    if not cabs or not drivers:
        conn.close()
        return jsonify({"error": "Active cabs and drivers are required for routing. Please ensure cabs and drivers are registered and set to Active."}), 400
        
    # Fetch companies
    cursor.execute('SELECT * FROM companies')
    companies = cursor.fetchall()
    company_map = {c["name"].lower(): c["id"] for c in companies}
    default_company_id = companies[0]["id"] if companies else 1
    
    # Simple clustering: group inquiries by service type & company
    clusters = {}
    for inq in inquiries:
        comp_name = inq["company"] or ""
        key = (inq["service_type"], comp_name)
        if key not in clusters:
            clusters[key] = []
        clusters[key].append(inq)
        
    created_count = 0
    import random
    
    cab_idx = 0
    drv_idx = 0
    
    for key, cluster_inqs in clusters.items():
        if cab_idx >= len(cabs) or drv_idx >= len(drivers):
            cab_idx = cab_idx % len(cabs)
            drv_idx = drv_idx % len(drivers)
            
        cab = cabs[cab_idx]
        driver = drivers[drv_idx]
        cab_idx += 1
        drv_idx += 1
        
        service_type, company_name = key
        
        company_id = default_company_id
        if company_name:
            for cname, cid in company_map.items():
                if company_name.lower() in cname or cname in company_name.lower():
                    company_id = cid
                    break
                    
        route_name = f"SMT HQ ➡️ {company_name or service_type}"
        created_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # Simple ETA in future (e.g. +45 mins)
        eta = "18:45"
        
        cursor.execute('''
            INSERT INTO trips (cab_id, driver_id, company_id, route_name, status, progress, speed, eta, created_at)
            VALUES (?, ?, ?, ?, 'Scheduled', 0.0, 0, ?, ?)
        ''', (cab["id"], driver["id"], company_id, route_name, eta, created_at))
        trip_id = cursor.lastrowid
        
        # Insert passengers
        for inq in cluster_inqs:
            cursor.execute('UPDATE inquiries SET status = "In Progress" WHERE id = ?', (inq["id"],))
            cursor.execute('''
                INSERT INTO trip_passengers (trip_id, name, stop_name, status)
                VALUES (?, ?, ?, 'Pending')
            ''', (trip_id, inq["name"], inq["details"] or "Tech Park Gate"))
            
        created_count += 1
        
    conn.commit()
    conn.close()
    return jsonify({"message": f"Optimization complete. Created {created_count} active trips routes.", "trips_created": created_count})


@app.route('/api/admin/trips/simulate-tick', methods=['POST'])
def simulate_tick():
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Fetch all active trips
    cursor.execute('SELECT * FROM trips WHERE status IN ("Scheduled", "En Route", "SOS Alert")')
    trips = cursor.fetchall()
    
    import random
    tick_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    alerts_added = 0
    
    for trip in trips:
        curr_progress = trip["progress"]
        curr_status = trip["status"]
        
        if curr_progress >= 100.0:
            cursor.execute('UPDATE trips SET status = "Completed", speed = 0, progress = 100.0 WHERE id = ?', (trip["id"],))
            cursor.execute('UPDATE trip_passengers SET status = "Dropped" WHERE trip_id = ?', (trip["id"],))
            continue
            
        new_progress = curr_progress + random.uniform(8.0, 18.0)
        if new_progress >= 100.0:
            new_progress = 100.0
            new_status = 'Completed'
            new_speed = 0
        else:
            new_status = 'En Route' if curr_status == 'Scheduled' else curr_status
            new_speed = random.randint(35, 75)
            
        cursor.execute('UPDATE trips SET progress = ?, status = ?, speed = ? WHERE id = ?', 
                       (new_progress, new_status, new_speed, trip["id"]))
        
        # EV Cab depletion logic
        cursor.execute('SELECT is_ev, charge_status, range_km FROM cabs WHERE id = ?', (trip["cab_id"],))
        cab = cursor.fetchone()
        if cab and cab["is_ev"] == 1:
            curr_soc = cab["charge_status"] if cab["charge_status"] is not None else 80
            curr_range = cab["range_km"] if cab["range_km"] is not None else 180
            new_soc = max(0, curr_soc - random.randint(2, 6))
            new_range = max(0, curr_range - random.randint(5, 15))
            cursor.execute('UPDATE cabs SET charge_status = ?, range_km = ? WHERE id = ?', (new_soc, new_range, trip["cab_id"]))
            
        # Passenger checks
        if new_progress >= 90.0:
            cursor.execute('UPDATE trip_passengers SET status = "Dropped" WHERE trip_id = ?', (trip["id"],))
        elif new_progress >= 30.0:
            cursor.execute('UPDATE trip_passengers SET status = "Onboard" WHERE trip_id = ? AND status = "Pending"', (trip["id"],))
            
        # Telemetry speeding/geofence alerts (8% chance)
        if new_status != 'Completed' and random.random() < 0.08:
            alert_type = random.choice(['Over Speeding', 'Geofence Breach'])
            details = ""
            if alert_type == 'Over Speeding':
                details = f"Vehicle speed flagged at {new_speed} km/h (Limit: 60 km/h) on Outer Ring Road corridor."
            else:
                details = "Vehicle drifted off route corridor. Automated geo-fence alert generated."
                
            cursor.execute('''
                INSERT INTO safety_alerts (trip_id, alert_type, details, status, created_at)
                VALUES (?, ?, ?, 'Active', ?)
            ''', (trip["id"], alert_type, details, tick_time))
            alerts_added += 1
            
        # SOS trigger chance (5% chance)
        if new_status not in ['Completed', 'SOS Alert'] and random.random() < 0.05:
            cursor.execute('UPDATE trips SET status = "SOS Alert", speed = 0 WHERE id = ?', (trip["id"],))
            cursor.execute('''
                INSERT INTO safety_alerts (trip_id, alert_type, details, status, created_at)
                VALUES (?, 'SOS Panic', 'Passenger SOS Panic Button Triggered. Cabin audio link initiated.', 'Active', ?)
            ''', (trip["id"], tick_time))
            alerts_added += 1
            
    conn.commit()
    conn.close()
    return jsonify({"message": "Simulation tick complete.", "alerts_generated": alerts_added})


@app.route('/api/admin/trips/<int:trip_id>/sos', methods=['POST'])
def trigger_sos(trip_id):
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('UPDATE trips SET status = "SOS Alert", speed = 0 WHERE id = ?', (trip_id,))
    created_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    cursor.execute('''
        INSERT INTO safety_alerts (trip_id, alert_type, details, status, created_at)
        VALUES (?, 'SOS Panic', 'Manual Dispatch SOS Panic Triggered by Operator.', 'Active', ?)
    ''', (trip_id, created_at))
    conn.commit()
    conn.close()
    return jsonify({"message": "SOS Panic Alarm broadcasted to vehicle."})


@app.route('/api/admin/trips/<int:trip_id>/resolve-sos', methods=['POST'])
def resolve_sos(trip_id):
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('UPDATE trips SET status = "En Route" WHERE id = ?', (trip_id,))
    cursor.execute('UPDATE safety_alerts SET status = "Resolved" WHERE trip_id = ?', (trip_id,))
    conn.commit()
    conn.close()
    return jsonify({"message": "Safety Alarm resolved. Vehicle returned to route grid."})


@app.route('/api/admin/trips/clear', methods=['DELETE'])
def clear_trips():
    if not check_admin_auth():
        return jsonify({"error": "Unauthorized Access"}), 401
        
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('DELETE FROM trip_passengers')
    cursor.execute('DELETE FROM safety_alerts')
    cursor.execute('DELETE FROM trips')
    cursor.execute('UPDATE inquiries SET status = "Pending" WHERE status = "In Progress"')
    conn.commit()
    conn.close()
    return jsonify({"message": "Simulation cleared and database tables reset."})


def _proxy_to(target_base, subpath=''):
    url = target_base.rstrip('/') + '/' + subpath.lstrip('/')
    if request.query_string:
        url += '?' + request.query_string.decode('utf-8', 'ignore')
    hop = {'host', 'cookie', 'content-length', 'origin'}
    headers = {k: v for k, v in request.headers if k.lower() not in hop}
    try:
        import requests as http
        upstream = http.request(
            method=request.method,
            url=url,
            headers=headers,
            data=request.get_data(),
            allow_redirects=False,
            timeout=(5, 90),
        )
    except Exception:
        return None
    skip = {'content-encoding', 'content-length', 'transfer-encoding', 'connection'}
    out_headers = [(k, v) for k, v in upstream.headers.items() if k.lower() not in skip]
    return Response(upstream.content, upstream.status_code, out_headers)


@app.route('/admin/invoices')
def admin_invoices_root():
    denied = require_staff_page()
    if denied:
        return denied
    return redirect('/admin/invoices/')


@app.route('/admin/invoices/')
@app.route('/admin/invoices/<path:filename>')
def admin_invoices(filename='index.html'):
    denied = require_staff_page()
    if denied:
        return denied
    return send_from_directory(invoices_dir, filename)


@app.route('/admin/trips', methods=['GET'])
def admin_trips():
    denied = require_staff_page()
    if denied:
        return denied
    return render_template('admin_trips.html')


@app.route('/admin/trips/generate', methods=['POST'])
def admin_trips_generate():
    denied = require_staff_page()
    if denied:
        return denied
    upload = request.files.get('excel_file')
    if not upload or not upload.filename:
        return render_template('admin_trips.html', error='Please choose an Excel (.xlsx) file.'), 400

    import importlib.util
    import tempfile

    spec = importlib.util.spec_from_file_location(
        'trip_sheet_generator',
        os.path.join(trips_dir, 'trip_sheet_generator.py')
    )
    trip_mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(trip_mod)

    watermark = os.path.join(trips_dir, 'hanuman.png')
    with tempfile.TemporaryDirectory() as tmp:
        excel_path = os.path.join(tmp, 'input.xlsx')
        pdf_path = os.path.join(tmp, 'Trip_Sheets.pdf')
        upload.save(excel_path)
        try:
            trip_mod.generate_trip_sheets(excel_path, pdf_path, watermark)
        except Exception as err:
            return render_template('admin_trips.html', error=str(err)), 400
        with open(pdf_path, 'rb') as pdf:
            data = pdf.read()
    resp = make_response(data)
    resp.headers['Content-Type'] = 'application/pdf'
    resp.headers['Content-Disposition'] = 'attachment; filename=Trip_Sheets.pdf'
    return resp


@app.route('/admin/dispatch/', defaults={'path': ''})
@app.route('/admin/dispatch/<path:path>', methods=['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'])
def admin_dispatch(path):
    denied = require_staff_page()
    if denied:
        return denied
    index = os.path.join(rac_dist_dir, 'index.html')
    if os.path.isfile(index):
        if path:
            wanted = os.path.normpath(os.path.join(rac_dist_dir, path))
            root = os.path.normpath(rac_dist_dir)
            if wanted.startswith(root + os.sep) and os.path.isfile(wanted):
                return send_from_directory(rac_dist_dir, path)
        return send_from_directory(rac_dist_dir, 'index.html')
    proxied = _proxy_to(RAC_FRONTEND_URL, ('admin/dispatch/' + path).strip('/'))
    if proxied is not None:
        return proxied
    proxied = _proxy_to(RAC_FRONTEND_URL, path)
    if proxied is not None:
        return proxied
    return render_template('dispatch_offline.html', configured=True), 503


if __name__ == '__main__':
    # Running locally
    app.run(host='0.0.0.0', port=5000, debug=True)
