services:
  - type: web
    name: smt-website
    runtime: python
    plan: free
    rootDir: shree-maruthi-travels-main/shree-maruthi-travels-main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120 backend.app:app
